### ISSUE TITLE
Further simplifications for water

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#54] opened 2021-04-17 23:52 UTC
First off, big thanks for the continued improvements to the _water_ css framework and its usability. 

I just converted two more packages to it, and I now use a 'standard' declaration of 

```yaml
output:
  minidown::mini_document:
    framework: water
    toc: true
    toc_float: true
```

which makes me think we could easily wrap this for a default `water_document` with the framework and toc options set.  In fact, I just implemented this here as a one-line and tested that, yes, toc can still be turned off.  Would you be interested in that as a really simple PR?  It would reduce the yaml footprint to, say, 

```yaml
output: minidown::water_document
```

I am open to other names, maybe `minidown::mini_document_water` or `...::mini_water_document` are more to your liking.

**Comment by atusy** [comment] 2021-04-20 12:09
@eddelbuettel I am really happy to hear it.

About the shortcut, this is duplicate of #45, which I opened based on your request.
I will add comments there.

**Closed by atusy** 2021-04-20 12:09 UTC
