### ISSUE TITLE
self_contained code blocks

### ISSUE THREAD

**Issue by DataHurdler** [atusy/minidown#89] opened 2023-06-21 15:58 UTC
When self_contained is set to true (default), there are extra lines between each line in multiline code blocks. But when self_contained is false, that goes away.

**Comment by atusy** [comment] 2023-06-27 22:43
Thanks, I'll take a look

**Comment by atusy** [comment] 2023-06-27 22:49
I cannot reproduce. Please show me a reproducible example.

Mine is the below.

````
---
output:
  minidown::mini_document:
    self_contained: false
---

self_contained is `false`

``` {r}
x <- 1
print(x)
```

bar
````

![image](https://github.com/atusy/minidown/assets/30277794/78e06750-fccb-4e14-9a80-81812e9e326f)

**Comment by atusy** [comment] 2023-07-07 15:21
I close this issue for now.
Feel free to reopen.

**Closed as completed by atusy** 2023-07-07 15:21 UTC
Labels: needs reprex
